// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpmelbovrxfyrckhwonf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwbWVsYm92cnhmeXJja2h3b25mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDU1MjIsImV4cCI6MjA2MzU4MTUyMn0.MKYJiKL6xAoPqCka9UjewDunHvQY1TUjTPgiFJOt1z0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);